version: "3.8"

services:
  backend-app-prod:
      build:
        context: .
        dockerfile: Containerfile
      container_name: backend-app-prod
      
      ports:
        - "8080:8080"
      volumes:
        - ./src:/app/src
        - ./test:/app/test
        - ./uploads:/app/uploads
      shm_size: '1gb'
      environment:
        PORT: 8080
        DB_HOST: host.docker.internal
        DB_PORT: 3306
        DB_USERNAME: uaga_user
        DB_PASSWORD: uaga_password
        DB_DATABASE: uagabd
        DB_SYNCHRONIZE: 'false'
        JWT_SECRET: your_super_secret_key
        CHROMIUM_EXECUTABLE_PATH: /usr/bin/chromium-browser
        CORS_ORIGINS: http://localhost:5173,http://localhost:3000,host.docker.internal:3000

  backend-app-dev:
    build:
      context: .
      dockerfile: Containerfile.dev
    container_name: backend-app-dev
    
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./uploads:/app/uploads
    shm_size: '1gb'
    environment:
      PORT: 8888
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USERNAME: uaga_user
      DB_PASSWORD: uaga_password
      DB_DATABASE: uagabd
      DB_SYNCHRONIZE: 'false'
      JWT_SECRET: your_super_secret_key
      CHROMIUM_EXECUTABLE_PATH: /usr/bin/chromium-browser
      CORS_ORIGINS: http://localhost:5173,http://localhost:3000,http://outro-dominio.com,host.docker.internal:3000