version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: frontend-app-dev
    ports:
      - "3000:3000"
    volumes:
      # Sincroniza sua pasta 'src' local com a do container
      - ./src:/app/src
    environment:
      # Garante que o hot-reload do Vite funcione corretamente no container
      - CHOKIDAR_USEPOLLING=true
      # Variável de ambiente com o caminho para o backend
      - VITE_API_BASE_URL=http://localhost:8888