version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uaga_password
      MYSQL_DATABASE: uagabd
      MYSQL_USER: uaga_user
      MYSQL_PASSWORD: uaga_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: backend-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: uaga_user
      DB_PASSWORD: uaga_password
      DB_DATABASE: uagabd
      DB_SYNCHRONIZE: 'false'
      JWT_SECRET: your_super_secret_key
