name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker-compose -f docker-compose.yml build

      - name: Start Services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be healthy
        timeout-minutes: 5 # Timeout para evitar que o job fique preso
        run: |
          echo "Waiting for backend service to be healthy..."
          while [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8888/api)" != "200" ]; do
            echo -n "."
            sleep 5
          done
          echo "Backend is healthy!"

      - name: Run Tests (opcional)
        # Este é um passo de exemplo. Adapte-o para seus comandos de teste.
        run: |
          docker-compose exec backend npm test
