FROM node:20-slim

# Atualiza e instala dependências do sistema necessárias para Cypress e Chromium
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg \
    libgtk-3-0 \
    libnss3 \
    libasound2 \
    libxss1 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxshmfence1 \
    libgbm1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxcb1 \
    libxtst6 \
    libpangocairo-1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    fonts-liberation \
    libappindicator3-1 \
    libdbus-1-3 \
    xvfb \
    dos2unix \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json yarn.lock ./

COPY . .

# Garante que o script de entrada seja executável e com formato Unix
RUN dos2unix ./entrypoint.sh && chmod +x ./entrypoint.sh

EXPOSE 3000

CMD ["./entrypoint.sh"]
